Added Schematic and PCB files needed for Ambient Light Sensor
UCSolarCarTeam/AltiumLibraries pull request #1
Opened 2017-01-06 20:15 UTC by bandakkalokka

2017-01-07 03:55 UTC, Logan-Hunter submitted a review, later dismissed
First thing - for the FFC  connector, you don't need the pads on the bottom, change the pad from multi-layer to top layer and it should do what you want. Also, for the schematic, most of our connectors only use the display name - if you click on the pin, you can turn the designator visibility off - since they're the same on yours, you definitely don't need it. For the sensor - if that model matches the actual physical dimensions of the part, you should probably extend the pads out a bit to make soldering easier. In addition, the pad one designator is usually a circle, not a rectangle. For the sensor schematic, you can also turn off the designators on the pins - the actual pin numbers don't matter for the schematic, only the pin functions, which is already well labeled.

2017-01-07 07:14 UTC, DanSGiesbrecht requested changes
-> Preface: I'll be basically repeating what Logan said, and adding to it.

**FFC Connector**

Schematic:
- Only use display name on pins (uncheck visible for pin designators)
- When linking .schlib to .pcblib by 'adding model' in schematic, you are not using a relative path. I had to select "PCB Library: Any" instead of "Library Path" for it to work on my machine. The name here will also have to be adjusted from "PCBComponent_1" as stated under 'PCB' comments.


PCB:
- pcb component name should match schematic component name. Currently, pcb component name is set to 'PCBCOMPONENT_1'.
- As Logan said, copper pads should only be on top layer, not multilayer. Double click on your pad, and in the 'Properties' section, in the 'Layer' drop-down, select 'Top Layer'.
- To comply with new components, silkscreen should be 0.2mm thick by default. The silkscreen edge should be no closer to a soldermask opening than 0.2mm, which should automatically be silk-to-copper spacing of 0.3mm (if soldermask expansion is set by the correct DRC). Look at the DC Barrel Jack in the same folder for reference. Make sure you are using the correct DRC. You should have the newest Barrel Jack library already in your working folder.
I find that the easiest way to lay down the silkscreen to meet spacing requirements is to set my grid to 0.025mm, and count 4 grids for 0.1mm and 8 for 0.2mm etc.
***The silkscreen detail is actually important to avoid throwing DRC errors for you or anyone that uses your part.***

Also, my bad for not communicating this to the team in advance. I had discussed it with Logan, but I have not yet made a proper conventions document. Sorry for that inconvenience.

**************************************************************************************************************

**LTR-329ALS-01**

Schematic:
- Looks good, I have no issues here.

PCB:
- Please apply same silkscreen changes as mentioned above to appease the DRC Gods.
- I believe you have used the measurements on page 3 of the datasheet (listed page 2/27) for your copper pad dimensions. Is this correct?
 These are the dimensions of the actual copper pad on the component, not the copper pad required on your PCB. Please use the dimensions on page 26 (listed page 25/27), titled "Recommended Land Pattern". If I'm not mistaken, increasing the pad size but not changing their position should fix this, but double check to make sure they are spaced the correct distance apart.
(Good catch on pad size Logan, I probably wouldn't have noticed that)
- Your 3D body is set to 1.2mm tall, instead of 0.7mm from the datasheet. You can change this by double clicking on the pink area indicating component body in the 2D editor view, and changing it under 'extruded' section of the menu.

**************************************************************************************************************

Sorry for the wall of text. I can tell that you put a lot of work into this, and it looks awesome. The tweaks Logan and I have listed, while in depth, are small fixes. Nice Job.

2017-01-13 04:10 UTC, bandakkalokka commented
Thank you for the comments!
The requested changes should be complete.
Please have a look and let us know if we missed anything or anything else needs to be changed.
Cheers!

2017-01-14 18:49 UTC, DanSGiesbrecht approved these changes

2017-01-14 22:15 UTC, merged